# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-27 04:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Url',
        ),
    ]
